# Generated by Django 3.2.12 on 2024-02-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240205_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motDepasse', models.CharField(blank=True, max_length=100)),
                ('dateCreation', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
