# Generated by Django 3.2.12 on 2024-02-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='mot_de_passe',
            new_name='mot_de_passe_généré',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
