# Generated by Django 3.2.12 on 2024-02-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20240228_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
